version: "2.0"

volumes:
  pgdata:
  esdata:

services:
  #
  # docker exec -it pg psql -u postgres
  #
  postgres:
    container_name: pg
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pa55w0rd
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - pghost



  #  mysql:
  #    container_name: mysql
  #    image: mariadb:latest
  #    restart: always
  #    environment:
  #      MYSQL_ROOT_PASSWORD: example
  #    volumes:
  #      - mysqldata:/var/lib/mysql

  # https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  # https://github.com/k-int/KBPlusG3/blob/dev-integration/SETUP-ES-DOCKER.txt
  # see https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  es5:
    container_name: es5
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
    restart: always
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node 
      - cluster.name=gokbg3-dev
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200 
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      default:
        aliases:
          - eshost
