---
grails:
  plugin:
    springsecurity:
      rest:
        token:
          storage:
            jwt:
              secret: "YourSecretWTKeyGoesHereItMustBeAtleast256BitsLongAndYouAbsolutelyShouldSetOneUpAndNotJustCopyThisDefaultValueOr-bad-things--TM-couldHappenToYou"
